name: Documentation Check

on:
  pull_request:

jobs:

  docs:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Verify documentation exists
        run: |
          test -d docs